version: '3.2'
volumes:
  exclusion1:
  exclusion2:
  exclusion3:
  exclusion4:
  exclusion5:
  exclusion6:
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        - CONFNAME=dev-site.conf
    ports:
      - ${DOCKER_PORT}:80
    depends_on:
      - php-fpm
  php-fpm:
    tty: true
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - ENVNAME=${ENVNAME}
    volumes:
      - .:/app:delegated
      - ./storage/logs:/app/storage/logs
    environment:
      DB_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    platform: linux/amd64
    # command: mysqld --innodb_use_native_aio=0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql_weather
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/db:/docker-entrypoint-initdb.d
